/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnviosRouteImport } from './routes/envios'
import { Route as DevolucionesRouteImport } from './routes/devoluciones'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductosSlugRouteImport } from './routes/productos.$slug'
import { Route as AdminProductosRouteImport } from './routes/admin.productos'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviosRoute = EnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => rootRouteImport,
} as any)
const DevolucionesRoute = DevolucionesRouteImport.update({
  id: '/devoluciones',
  path: '/devoluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductosSlugRoute = ProductosSlugRouteImport.update({
  id: '/productos/$slug',
  path: '/productos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/devoluciones': typeof DevolucionesRoute
  '/envios': typeof EnviosRoute
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/devoluciones': typeof DevolucionesRoute
  '/envios': typeof EnviosRoute
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/devoluciones': typeof DevolucionesRoute
  '/envios': typeof EnviosRoute
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrito'
    | '/catalogo'
    | '/checkout'
    | '/contacto'
    | '/devoluciones'
    | '/envios'
    | '/login'
    | '/privacidad'
    | '/terminos'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/productos/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrito'
    | '/catalogo'
    | '/checkout'
    | '/contacto'
    | '/devoluciones'
    | '/envios'
    | '/login'
    | '/privacidad'
    | '/terminos'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/productos/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carrito'
    | '/catalogo'
    | '/checkout'
    | '/contacto'
    | '/devoluciones'
    | '/envios'
    | '/login'
    | '/privacidad'
    | '/terminos'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/productos/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CarritoRoute: typeof CarritoRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactoRoute: typeof ContactoRoute
  DevolucionesRoute: typeof DevolucionesRoute
  EnviosRoute: typeof EnviosRoute
  LoginRoute: typeof LoginRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TerminosRoute: typeof TerminosRoute
  ProductosSlugRoute: typeof ProductosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envios': {
      id: '/envios'
      path: '/envios'
      fullPath: '/envios'
      preLoaderRoute: typeof EnviosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devoluciones': {
      id: '/devoluciones'
      path: '/devoluciones'
      fullPath: '/devoluciones'
      preLoaderRoute: typeof DevolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/productos/$slug': {
      id: '/productos/$slug'
      path: '/productos/$slug'
      fullPath: '/productos/$slug'
      preLoaderRoute: typeof ProductosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CarritoRoute: CarritoRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  ContactoRoute: ContactoRoute,
  DevolucionesRoute: DevolucionesRoute,
  EnviosRoute: EnviosRoute,
  LoginRoute: LoginRoute,
  PrivacidadRoute: PrivacidadRoute,
  TerminosRoute: TerminosRoute,
  ProductosSlugRoute: ProductosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
